#! /usr/bin/make -f
# $Id$

default: clean

main: DiscordsRun.o DistanceMatrix.o Utils.o FileUtils.o main.o
main.phi: DiscordsRun.o.phi DistanceMatrix.o.phi Utils.o.phi FileUtils.o.phi main.o.phi

include $(ROOT)Makefile.Rules






